variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  image: registry.gitlab.com/sancloudltd/buildimg/gcc-arm-8.3:latest
  before_script:
    - rclone config create b2 b2 account $B2_KEY_ID key $B2_APP_KEY > /dev/null
    - git config --global user.name "Sancloud CI"
    - git config --global user.email "noreply@sancloud.co.uk"
  script:
    - ./scripts/ci-build.sh
    - rclone copy --ignore-existing build/sstate-cache/ b2:sc-yocto/arago/sstate-thud/
    - rclone copy --ignore-existing build/tmp/deploy/sources/mirror/ b2:sc-yocto/mirror/
    - rclone sync images-bbe/ b2:sc-yocto/arago/builds/$CI_COMMIT_REF_SLUG/
